/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace excaliburST {

using System;
using System.Runtime.InteropServices;

public class t_ExcDevInfoPacket : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal t_ExcDevInfoPacket(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(t_ExcDevInfoPacket obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~t_ExcDevInfoPacket() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stfuncsPINVOKE.delete_t_ExcDevInfoPacket(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public uint fWorkingState {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_fWorkingState_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_fWorkingState_get(swigCPtr);
      return ret;
    } 
  }

  public uint fRegistryDeviceValid {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_fRegistryDeviceValid_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_fRegistryDeviceValid_get(swigCPtr);
      return ret;
    } 
  }

  public uint fFlag3 {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_fFlag3_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_fFlag3_get(swigCPtr);
      return ret;
    } 
  }

  public uint fFlag4 {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_fFlag4_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_fFlag4_get(swigCPtr);
      return ret;
    } 
  }

  public uint fFlag5 {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_fFlag5_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_fFlag5_get(swigCPtr);
      return ret;
    } 
  }

  public uint fFlag6 {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_fFlag6_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_fFlag6_get(swigCPtr);
      return ret;
    } 
  }

  public uint dwBusType {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_dwBusType_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_dwBusType_get(swigCPtr);
      return ret;
    } 
  }

  public uint dwBoardType {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_dwBoardType_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_dwBoardType_get(swigCPtr);
      return ret;
    } 
  }

  public uint dwSocketNumber {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_dwSocketNumber_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_dwSocketNumber_get(swigCPtr);
      return ret;
    } 
  }

  public uint dwRegistryDevice {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_dwRegistryDevice_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_dwRegistryDevice_get(swigCPtr);
      return ret;
    } 
  }

  public uint dwDword5 {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_dwDword5_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_dwDword5_get(swigCPtr);
      return ret;
    } 
  }

  public uint dwDword6 {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_dwDword6_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_dwDword6_get(swigCPtr);
      return ret;
    } 
  }

  public uint dwDword7 {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_dwDword7_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_dwDword7_get(swigCPtr);
      return ret;
    } 
  }

  public uint dwDword8 {
    set {
      stfuncsPINVOKE.t_ExcDevInfoPacket_dwDword8_set(swigCPtr, value);
    } 
    get {
      uint ret = stfuncsPINVOKE.t_ExcDevInfoPacket_dwDword8_get(swigCPtr);
      return ret;
    } 
  }

  public t_ExcDevInfoPacket() : this(stfuncsPINVOKE.new_t_ExcDevInfoPacket(), true) {
  }

}

}
